name: CI (all tests - unit, integrated, performance)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: 18
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: integrationTest performanceTest build --continue
